### ISSUE TITLE
warning on each run of prefect command under 2.7

### ISSUE THREAD

**Issue by cwhatley** [PrefectHQ/prefect-slack#41]
Every prefect command and flow run outputs this warning when prefect_slack is installed:

```.../site-packages/prefect/utilities/dispatch.py:162: UserWarning: Type 'SlackWebhook' at .../site-packages/prefect_slack/credentials.py:43 has key 'slack-webhook' that matches existing registered type 'SlackWebhook' from .../site-packages/prefect/blocks/notifications.py:82. The existing type will be overridden.```

**Comment by john-jam** [comment]
We also hit this warning on every run. What can we do to avoid loading the `slack-webhook` at `site-packages/prefect/blocks/notifications.py`?

**Comment by ahuang11** [comment]
Apologize for the late response; this should be fixed in https://github.com/PrefectHQ/prefect-slack/pull/45
